### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by Guilouf** [dsoprea/PyEasyArchive#35]
I tried this with a tar file:
```python
with open(archive.temporary_file_path(), 'rb') as f:
    for entry in libarchive.public.memory_pour(f.read()):
        print(entry)
```
It kind of worked because the filepath were printed (sometimes), but it ended by a
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` which is
a segmentation fault that by the way ended all the python process

**Comment by tripleee** [comment]
This is unrelated to anything in the library, it happens when you attempt to `print` in an environment which doesn't support Unicode properly (or more broadly anything other than 7-bit ASCII). On Unix-like systems, fix your locale settings. On Windows, I can't tell you in much detail; perhaps `chcp 65001` if your platform supports that.

**Comment by Guilouf** [comment]
Im on kubuntu and i never had an issue with Unicode support. I ended up with using the standard python libs, `tar` and `zip`.
But i should be more precise in order to make this issue reproducible.

**Comment by ievans** [comment]
@tripleee @Guilouf I have a zip archive with non-ASCII filenames which exhibits a similar issue (original bug report is a bit unclear, I think, on where the error is). Here's my code + traceback:

```
...
for entry in libarchive.public.memory_pour(f.read()):
    print(entry.pathname)
```

```
...libarchive/adapters/archive_entry.py, line 114, in _archive_entry_pathname
    return _archive_entry_pathname(self.__entry_res)
...libarchive/adapters/archive_entry.py, line 15, in _archive_entry_pathname
    return filepath.decode(_ASCII_ENCODING)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 790: ordinal not in range(128)
```

(on OSX 10.14.5, Python 3.7.3)

**Comment by dsoprea** [comment]
Yeah. I think this is a non-issue. I just added test coverage for Unicode in the filenames and the content just to make sure that this continues to work:

https://github.com/dsoprea/PyEasyArchive/commit/2c8b50bd70468f54e7690cec1ac747e3a20ddf10

I just realized that these changes were unreleased. I just pushed a release to Github and PyPI:

https://pypi.org/project/libarchive/0.4.7/#files
https://github.com/dsoprea/PyEasyArchive/releases/tag/0.4.7

**Comment by ievans** [comment]
@dsoprea sweet, thank you!

**Comment by alexwh** [comment]
https://github.com/dsoprea/PyEasyArchive/blob/cc2345e71408402c11274a3b35b562aeede0e41d/libarchive/adapters/archive_read.py#L61 is missing these changes.

**Comment by ganego** [comment]
Bump, since it still fails opening a file with a non-ASCII letter in it, as @alexwh pointed out.

https://github.com/dsoprea/PyEasyArchive/blob/master/libarchive/adapters/archive_read.py#L61
